# Site settings
title: andilabs
email: andi@andilabs.com
description: > # this means to ignore newlines until "baseurl:"
  This is a microblog of andilabs
  for sharing nice pices of code, cool libraries + tools and clever ideas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andilabs.com" # the base hostname & protocol for your site
twitter_username: andilabs
github_username:  andilabs

# Build settings
markdown: kramdown
